package render

import (
	"fmt"
	"strings"
	"time"

	"github.com/RamazanKara/vramwatch/internal/model"
)

const (
	svgWidth   = 760
	svgPadding = 24
	svgBarW    = svgWidth - 2*svgPadding
	svgBarH    = 40
	svgFont    = "ui-monospace, 'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace"
	svgBG      = "#0d1117"
	svgFG      = "#e6edf3"
	svgMuted   = "#8b949e"
	svgTrack   = "#161b22"
)

// SVG renders a branded scorecard for the snapshot: a dark card with a stacked
// VRAM bar and legend per GPU. Deterministic given identical input.
func SVG(snap model.Snapshot) string {
	// Measure height.
	y := 84 // header
	for _, bd := range snap.Breakdowns {
		y += 30                            // title
		y += svgBarH + 18                  // bar
		y += len(orderedSegments(bd)) * 22 // legend
		if bd.Prediction != nil {
			y += 26
		}
		y += 18 // gap
	}
	y += 36 // footer
	height := y

	var b strings.Builder
	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d" font-family="%s">`,
		svgWidth, height, svgWidth, height, svgFont)
	fmt.Fprintf(&b, `<rect x="0" y="0" width="%d" height="%d" rx="14" fill="%s"/>`, svgWidth, height, svgBG)

	// Header.
	fmt.Fprintf(&b, `<text x="%d" y="46" font-size="26" font-weight="700" fill="%s">vramwatch</text>`, svgPadding, svgFG)
	meta := snapMeta(snap)
	if meta != "" {
		fmt.Fprintf(&b, `<text x="%d" y="46" text-anchor="end" font-size="13" fill="%s">%s</text>`,
			svgWidth-svgPadding, svgMuted, escapeXML(meta))
	}
	fmt.Fprintf(&b, `<line x1="%d" y1="62" x2="%d" y2="62" stroke="%s" stroke-width="1"/>`,
		svgPadding, svgWidth-svgPadding, svgTrack)

	cursor := 84
	for i, bd := range snap.Breakdowns {
		cursor = renderSVGBreakdown(&b, bd, i, cursor)
	}

	// Footer.
	fmt.Fprintf(&b, `<text x="%d" y="%d" font-size="12" fill="%s">generated by vramwatch · github.com/RamazanKara/vramwatch</text>`,
		svgPadding, height-16, svgMuted)
	b.WriteString(`</svg>`)
	return b.String()
}

func renderSVGBreakdown(b *strings.Builder, bd model.Breakdown, idx, y int) int {
	g := bd.GPU
	title := fmt.Sprintf("GPU %d · %s", g.Index, g.Name)
	sub := string(g.Vendor)
	if g.Driver != "" {
		sub += " · driver " + g.Driver
	}
	fmt.Fprintf(b, `<text x="%d" y="%d" font-size="15" font-weight="600" fill="%s">%s</text>`,
		svgPadding, y+4, svgFG, escapeXML(title))
	fmt.Fprintf(b, `<text x="%d" y="%d" text-anchor="end" font-size="12" fill="%s">%s / %s</text>`,
		svgWidth-svgPadding, y+4, svgMuted, model.HumanBytes(bd.Used()), model.HumanBytes(g.TotalBytes))
	fmt.Fprintf(b, `<text x="%d" y="%d" font-size="12" fill="%s">%s</text>`, svgPadding, y+20, svgMuted, escapeXML(sub))
	y += 30

	// Bar with rounded clip.
	segs := orderedSegments(bd)
	clip := fmt.Sprintf("bar%d", idx)
	fmt.Fprintf(b, `<clipPath id="%s"><rect x="%d" y="%d" width="%d" height="%d" rx="8"/></clipPath>`,
		clip, svgPadding, y, svgBarW, svgBarH)
	fmt.Fprintf(b, `<rect x="%d" y="%d" width="%d" height="%d" rx="8" fill="%s"/>`, svgPadding, y, svgBarW, svgBarH, svgTrack)
	fmt.Fprintf(b, `<g clip-path="url(#%s)">`, clip)
	total := g.TotalBytes
	if total == 0 {
		total = 1
	}
	x := float64(svgPadding)
	for i, s := range segs {
		w := float64(svgBarW) * float64(s.Bytes) / float64(total)
		if i == len(segs)-1 {
			w = float64(svgPadding+svgBarW) - x // last segment fills to the end
		}
		fmt.Fprintf(b, `<rect x="%.2f" y="%d" width="%.2f" height="%d" fill="%s"/>`, x, y, w, svgBarH, styleFor(s.Kind).hex)
		x += w
	}
	b.WriteString(`</g>`)
	y += svgBarH + 18

	// Legend.
	for _, s := range segs {
		st := styleFor(s.Kind)
		fmt.Fprintf(b, `<rect x="%d" y="%d" width="12" height="12" rx="2" fill="%s"/>`, svgPadding, y-11, st.hex)
		label := s.Label
		if s.Estimated {
			label += " (est.)"
		}
		fmt.Fprintf(b, `<text x="%d" y="%d" font-size="13" fill="%s">%s</text>`, svgPadding+20, y, svgFG, escapeXML(label))
		fmt.Fprintf(b, `<text x="%d" y="%d" text-anchor="end" font-size="13" fill="%s">%s</text>`,
			svgPadding+300, y, svgFG, model.HumanBytes(s.Bytes))
		fmt.Fprintf(b, `<text x="%d" y="%d" text-anchor="end" font-size="13" fill="%s">%.1f%%</text>`,
			svgPadding+380, y, svgMuted, pct(s.Bytes, g.TotalBytes))
		y += 22
	}

	// Prediction.
	if p := bd.Prediction; p != nil {
		col := svgMuted
		prefix := "predict"
		if p.OOMRisk {
			col = "#f85149"
			prefix = "⚠ OOM risk"
		}
		msg := fmt.Sprintf("%s: headroom %s · ~%s/token · max ctx ≈ %s tok",
			prefix, model.HumanBytes(p.HeadroomBytes), model.HumanBytes(p.KVBytesPerToken), formatInt(p.MaxContextFits))
		fmt.Fprintf(b, `<text x="%d" y="%d" font-size="13" fill="%s">%s</text>`, svgPadding, y, col, escapeXML(msg))
		y += 26
	}
	return y + 18
}

func snapMeta(snap model.Snapshot) string {
	var parts []string
	if snap.Host != "" {
		parts = append(parts, snap.Host)
	}
	if !snap.Timestamp.IsZero() {
		parts = append(parts, snap.Timestamp.Format(time.RFC3339))
	}
	return strings.Join(parts, " · ")
}

func escapeXML(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return r.Replace(s)
}
